before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Tag }}"
  replacements:
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
blob:
- 
  provider: gs
  bucket: goreleaser-bucket
- 
  provider: s3
  bucket: goreleaser-bucket

release:
  disable: true